//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ContactDataAccess;
    using System.Data.Entity.Validation;
    using System.Data.Entity.ModelConfiguration;
    using System.Reflection;


    public partial class MessagesDatabaseEntities : DbContext
    {
        public MessagesDatabaseEntities()
            : base("name=MessagesDatabaseEntities")
        {
        }

        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException e)
            {
                var newException = new DbEntityValidationException("invalid value");
                throw newException;
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<MessagesTopics>().HasMany(p => p.).WithMany();
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactsDetails> ContactsDetails { get; set; }
        public virtual DbSet<MessagesTable> MessagesTable { get; set; }
        public virtual DbSet<MessagesTopics> MessagesTopics { get; set; }
    }
}
